# Generated by Django 4.2.11 on 2025-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_name', models.CharField(max_length=100)),
                ('App_pass', models.CharField(max_length=100)),
                ('User_pass', models.CharField(max_length=100)),
                ('email_pass', models.EmailField(max_length=254)),
                ('password_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
